-- Prepare `projects` to mirror the Baserow "Projects" table (1044048).
--
-- Baserow is the source of truth; this table becomes a read mirror that the
-- frontend queries. Scope of this migration is projects only — tasks, phases,
-- sub tasks and engineers follow in later steps.

-- ---------------------------------------------------------------------------
-- Link column
-- ---------------------------------------------------------------------------
-- Baserow row ids are integers and sparse (rows 25 and 28-39 are already
-- deleted), so the link has to be stored explicitly. It is the key the sync
-- upserts on: null for rows created in the tracker, set for mirrored rows.
alter table projects
  add column if not exists baserow_id integer;

create unique index if not exists idx_projects_baserow_id
  on projects(baserow_id)
  where baserow_id is not null;

-- ---------------------------------------------------------------------------
-- Columns that exist in Baserow but had no home here
-- ---------------------------------------------------------------------------
alter table projects
  -- Baserow "Client": the customer (District Assembly, ENI, Ghana Gas, ...).
  -- Distinct from company_id, which is the MacWest/Cypress/Northbrook entity.
  add column if not exists client text,
  -- Baserow "Tender Stage": the bid pipeline. Drives the Status formula.
  add column if not exists tender_stage text,
  -- Baserow "Progress percent": avg(lookup('Phases','Progress Tasks')).
  -- Computed in Baserow, so read-only here.
  add column if not exists progress_percent numeric(5,2),
  -- Baserow "Budget", distinct from the existing actual_cost.
  add column if not exists budget numeric;

-- ---------------------------------------------------------------------------
-- contract_value must accept null
-- ---------------------------------------------------------------------------
-- Projects still at bid stage have no contract value yet. Four such rows exist
-- in Baserow today; without this they cannot be mirrored at all.
alter table projects
  alter column contract_value drop not null;

-- ---------------------------------------------------------------------------
-- Widen the status constraint
-- ---------------------------------------------------------------------------
-- Baserow's Status formula emits: Bidding | Scheduled | Active | Completed.
-- The existing constraint allows only active|completed|on_hold. on_hold is
-- retained because it may already be in use by tracker-created rows.
--
-- The constraint name was generated by the dashboard rather than a migration,
-- so it is located dynamically instead of assumed.
do $$
declare
  c record;
begin
  for c in
    select conname
    from pg_constraint
    where conrelid = 'public.projects'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%status%'
  loop
    execute format('alter table public.projects drop constraint %I', c.conname);
  end loop;
end $$;

alter table projects
  add constraint projects_status_check
  check (status in ('bidding', 'scheduled', 'active', 'completed', 'on_hold'));

-- ---------------------------------------------------------------------------
-- Supporting indexes
-- ---------------------------------------------------------------------------
create index if not exists idx_projects_tender_stage on projects(tender_stage);

comment on column projects.baserow_id is
  'Baserow Projects (table 1044048) row id. Null for tracker-created rows.';
comment on column projects.progress_percent is
  'Mirrored from the Baserow formula field; recomputed there, never written here.';
